const mongoose=require('mongoose');
const recipeSchema=new mongoose.Schema({
    id:{
        type:Number,
        unique:true 
    },
    name:{
        type:String,
        required:true,
        unique:true,
        trim:true
    },
    ingredients:{
        type:Array,
        required:true,
    },
    instructions:{
        type:Array,
        required:true,
    },
    prepTimeMinutes:{
        type:Number,
        required:true
    },
    cookTimeMinutes:{
        type:Number,
        required:true
    },
    servings:{
        type:Number,
        required:true
    },
    difficulty:{
        type:String,
    },
    cuisine:{
        type:String,
        trim:true,
    },
    calories:{
        type:Number
    },
    tags:{
        type:Array,
    },
    rating:{
        type:Number,
    },
    mealType:{
        type:Array
    }
});
module.exports=mongoose.model("Recipes",recipeSchema);